// <auto-generated />
namespace TrulySkilled.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class RelationshipUpdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationshipUpdates));
        
        string IMigrationMetadata.Id
        {
            get { return "201310190424317_RelationshipUpdates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
