// <auto-generated />
namespace TrulySkilled.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GameModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201310051930028_GameModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
